### ISSUE TITLE
Autores

### ISSUE THREAD

**Issue by bcessa** [EL-BID/IDBx-Data-Engine#2]
Hola, el link que tienen para __Carlos Macher Barcenas__ en el archivo README no funciona
`https://github.com/EL-BID/IDBx-Data-Engine/blob/master/carlosm@iadb.org`

Adicionalmente me parece que les faltaron al menos un par de nombres en los autores originales 😊

**Comment by bid-code4dev** [comment]
Gracias por reportar el link caido! ya lo actualizamos. 
Con respecto a los autores originales, déjanos hacer las consultas pertinentes para proceder con la actualización. 👍

**Comment by bcessa** [comment]
__Después de 6 meses sin ningún tipo de respuesta__ cierro el issue por falta de interés de su parte en arreglarlo 👍

Solo para dejar constancia: Es una __violación de las licencias de código abierto__ no respetar/reconocer la autoría original de las herramientas que intentan "promover" 😉

**Comment by bcessa** [comment]
Un comentario adicional para dejar constancia de que mi comentario anterior es __incorrecto__. El equipo de @knlopenknowledge __si estuvo, y continua, trabajando en el seguimiento de este punto.__ El error estuvo en mi falta de comunicación con ellos para mantenerme al tanto de sus avances y esfuerzos.

Públicamente una disculpa a todo el equipo, y gracias por su continuo apoyo y esmero en atención a esta solicitud.
